Update test_philos_jaka

diff --git a/test_philos_jaka b/test_philos_jaka
--- a/test_philos_jaka
+++ b/test_philos_jaka
@@ -90,8 +90,12 @@ ARGS=(
 		"1 800 200 200"\
 		"2 200 200 200"\
 		"2 310 200 100"\
-		"4 200 205 200")
+		"4 200 205 200"
+)
+
+# TURN ON / OFF
 ARRLEN=${#ARGS[@]}
+# ARRLEN=0
 
 # j=0
 # while [ $j -lt $CYCLES ]
@@ -128,57 +132,79 @@ ARGS=(
 	"100 800  200 200"\
 	"105 800  200 200"\
 	"200 800  200 200"
-	)
+)
+	
+# TURN ON / OFF
 ARRLEN=${#ARGS[@]}
+# ARRLEN=0
 
-# j=0
-# while [ $j -lt $CYCLES ]
-# do
-# 	echo -e "\n${CYN}---------------------------------------------------------------------------- ${RES}"
-# 	echo -e "${CYN}SHOULD NOT DIE, runtime $TIME secs --------------------------------------------- ${RES}\n"
-# 	echo -e "${CYN}   CYCLE $j ${RES}"
-# 	echo "CYCLE $j" >> output_lastlines
-# 	i=0
-# 	while [ $i -lt $ARRLEN ]
-# 	do
-# 		echo -e -n "   Test $i:	${ARGS[$i]}"
-# 		echo -e "\n\n\n--- SHOULD NOT DIE, CYCLE $j, TEST $i ---" >> output_error
-# 		$TIMEOUT $TIME $FOLDERPATH/philo	${ARGS[$i]} 2>> output_error 1> output ; sleep 1
-# 		python3 output_check_order.py
-# 		ORDER=$?
-# 		RET=$(grep -c 'died' output)
+j=0
+while [ $j -lt $CYCLES ]
+do
+	echo -e "\n${CYN}---------------------------------------------------------------------------- ${RES}"
+	echo -e "${CYN}SHOULD NOT DIE, runtime $TIME secs --------------------------------------------- ${RES}\n"
+ 	echo -e "${CYN}   CYCLE $j ${RES}"
+ 	echo "CYCLE $j" >> output_lastlines
+ 	i=0
+ 	while [ $i -lt $ARRLEN ]
+ 	do
+ 		echo -e -n "   Test $i:	${ARGS[$i]}"
+ 		echo -e "\n\n\n--- SHOULD NOT DIE, CYCLE $j, TEST $i ---" >> output_error
+ 		$TIMEOUT $TIME $FOLDERPATH/philo	${ARGS[$i]} 2>> output_error 1> output ; sleep 1
+ 		# python3 output_check_order.py
+		python3 ../PHILO_TESTER_JAKA/output_check_order.py
+ 		ORDER=$?
+ 		RET=$(grep -c 'died' output)
 
-# 		if ! [ -s output ]; then
-# 			RET=-1
-# 		fi
+ 		if ! [ -s output ]; then
+ 			RET=-1
+ 		fi
 
 
-# 		check_last_lines $i
-# 		CHECK=$?
-# 		if [ $RET == 0 ] && [ $ORDER == 0 ]; then
-# 			if [ $CHECK == 0 ]; then
-# 				echo -e " .... $OK \n" ; sleep 1
-# 			fi
-# 		elif [ $RET == 1 ] && [ $ORDER == 0 ]; then
-#  			echo -e "$RED .... died too soon (maybe due to fsanitize) $RES \n" ; sleep 1
-# 		elif [ $RET == 1 ] && [ $ORDER == 1 ]; then
-#  			echo -e "$RED .... died too soon (maybe due to fsanitize) $RES \n" ; sleep 1
-# 		elif [ $RET == -1 ] ; then
-# 			echo -e "$RED .... empty output file (maybe runtime was too short)$RES\n"
-# 		fi
-# 		RET=$(grep -c 'data race' output_error)
-# 		if [ $RET -gt 0 ]; then
-# 			echo -e "$RED $RET .... Data Race found!\n $RES"
-# 		fi
-# 		((i++))
-# 	done
-# 	((j++))
-#  done
+ 		check_last_lines $i
+ 		CHECK=$?
+ 		if [ $RET == 0 ] && [ $ORDER == 0 ]; then
+ 			if [ $CHECK == 0 ]; then
+ 				echo -e " .... $OK \n" ; sleep 1
+ 			fi
+ 		elif [ $RET == 1 ] && [ $ORDER == 0 ]; then
+  			echo -e "$RED .... died too soon (maybe due to fsanitize) $RES \n" ; sleep 1
+ 		elif [ $RET == 1 ] && [ $ORDER == 1 ]; then
+  			echo -e "$RED .... died too soon (maybe due to fsanitize) $RES \n" ; sleep 1
+ 		elif [ $RET == -1 ] ; then
+ 			echo -e "$RED .... empty output file (maybe runtime was too short)$RES\n"
+ 		fi
+ 		RET=$(grep -c 'data race' output_error)
+ 		if [ $RET -gt 0 ]; then
+ 			echo -e "$RED $RET .... Data Race found!\n $RES"
+ 		fi
+ 		((i++))
+ 	done
+ 	((j++))
+done
 
 
 
 ##################################################################################
 ###  SHOULD STOP AFTER x MEALS  ##################################################
+
+ARGS=(  
+	"  2 710  300 100"\
+	"  4 410  200 200"\
+	#"  5 800  200 200"\
+	"  5 1000 200 200"\
+	"  5 600  150 150"\
+	#"  7 800  200 100"\
+	#"  7 800  100 300"\
+	"100 800  200 200"\
+	"105 800  200 200"\
+	"200 800  200 200"
+)
+	
+# TURN ON / OFF
+ARRLEN=${#ARGS[@]}
+# ARRLEN=0
+
 
 j=0
 while [ $j -lt $CYCLES ]
