Added timeout to meals-test

diff --git a/test_philos_jaka b/test_philos_jaka
--- a/test_philos_jaka
+++ b/test_philos_jaka
@@ -4,6 +4,7 @@ RED="\033[0;31m"
 CYN="\033[0;36m"
 GRN="\033[0;32m"
 BLU="\033[0;34m"
+YEL="\033[1;33m"
 RES="\033[0m"
 
 
@@ -11,7 +12,7 @@ RES="\033[0m"
 #
 #	On Mac, must be installed brew Coreutils, for gtimeout
 #
-#	The test folder should be next to the philo folder (or change variable PHILOPATH)
+#	The test folder should be next to the philo folder (or change the variable FOLDERPATH)
 #
 #	Each output goes into file "output", temporarily.
 #	Sterr goes into file "output_erorr"
@@ -24,7 +25,7 @@ RES="\033[0m"
 #	SET VARIABLES:
       TIME=11     	# Set the runtime of each test, in seconds
       MEALS=20     	# Max nr of meals (only for the last group of tests)
-      CYCLES=3     	# How many times to perform each group of tests 
+      CYCLES=1     	# How many times to perform each group of tests 
       FOLDERPATH="../philo"
 
 #
@@ -36,7 +37,7 @@ RES="\033[0m"
 
 
 
-cd ../philo && make re && cd ../test_philos_jaka
+cd ../philo && make re && cd ../philo_tester_jaka
 
 
 # CLEAR THE FILE FROM PREVIOUS OUTPUT
@@ -47,21 +48,16 @@ echo "" > output_error
 OK="${GRN} OK ${RES}"
 KO="${RED} KO ${RES}"
 
-# echo ".-,--. .     .        ,--,--'      .            ,-_/            "
-# echo "'|__/ |-. . |  ,-.   `-`| ,-. ,-. |- ,-. ,-.   '  | ,-. . , ,-. "
-# echo ".|    | | | |  | |    , | |-' `-.`|  |-' |        | ,-| |/  ,-| "
-# echo "`'    ' ' ' `' `-'    `-' `-' `-' `' `-' '        | `-^`|\  `-^ "
-# echo "                  `~~`                     `~~/  |`     ' `     "
-# echo "                                               `--'  "
 
-echo -e "\n\n\n$GRN"
-echo "   ___  _      _  _            _____            _                  __          _          "
-echo "  / _ \| |__  (_)| |  ___     /__   \ ___  ___ | |_  ___  _ __     \ \   __ _ | | __  __ _ "
-echo " / /_)/| \_ \ | || | / _ \      / /\// _ \/ __|| __|/ _ \| __|      \ \  / _ || |/ //_  |"
-echo "/ ___/ | | | || || || (_) |    / /  |  __/\__ \| |_|  __/| |     /\_/ /| (_| ||  <| (_| |"
-echo "\/     |_| |_||_||_| \___/_____\/    \___||___/ \__|\___||_|_____\___/  \__,_||_|\_\\__,_|"
-echo "                         |_____|                           |_____|                        "
-echo -e "\n\n\n$RES"
+
+
+echo -e "\n\n\n$YEL"
+echo "   ___  _      _  _          _____            _                __          _          "; sleep 0.1
+echo "  / _ \| |__  (_)| |  ___   /__   \ ___  ___ | |_  ___  _ __   \ \    ___ | | __ ___ " ; sleep 0.1
+echo " / /_)/| \_ \ | || | / _ \    / /\// _ \/ __|| __|/ _ \| __|    \ \ / _  || |/ //_  |" ; sleep 0.1
+echo "/ ___/ | | | || || || (_) |  / /  |  __/\__ \| |_|  __/| |   /\_/ /| (_| ||  <| (_| |" ; sleep 0.1
+echo "\/     |_| |_||_||_| \___/   \/    \___||___/ \__|\___||_|   \___/  \__,_||_|\_\ __ |" ; sleep 0.1
+echo -e "\n$RES"
 
 sleep 1
 
@@ -97,25 +93,25 @@ ARGS=(
 		"4 200 205 200")
 ARRLEN=${#ARGS[@]}
 
-j=0
-while [ $j -lt $CYCLES ]
-	do
-	echo -e "${CYN}\n--------------------------------------------------------------------- ${RES}"
-	echo -e "${CYN}SHOULD DIE: --------------------------------------------------------- ${RES}\n"
-	echo -e "${CYN}   CYCLE $j ${RES}"
-	i=0
-	while [ $i -lt $ARRLEN ]
-		do
-			echo -e "\n\n\n--- SHOULD DIE, CYCLE $j, TEST $i ---" >> output_error
-			$TIMEOUT 10 $FOLDERPATH/philo ${ARGS[$i]} 2>> output_error 1> output
-			RET=$(grep -c 'died' output)
-			if [ $RET = 1 ]; then
-				echo -e "   ${ARGS[$i]}     $GRN died  OK $RES \n"
-			fi
-			((i++))
-	done
-	((j++))
-done
+# j=0
+# while [ $j -lt $CYCLES ]
+# 	do
+# 	echo -e "${CYN}\n--------------------------------------------------------------------- ${RES}"
+# 	echo -e "${CYN}SHOULD DIE: --------------------------------------------------------- ${RES}\n"
+# 	echo -e "${CYN}   CYCLE $j ${RES}"
+# 	i=0
+# 	while [ $i -lt $ARRLEN ]
+# 		do
+# 			echo -e "\n\n\n--- SHOULD DIE, CYCLE $j, TEST $i ---" >> output_error
+# 			$TIMEOUT 10 $FOLDERPATH/philo ${ARGS[$i]} 2>> output_error 1> output
+# 			RET=$(grep -c 'died' output)
+# 			if [ $RET = 1 ]; then
+# 				echo -e "   ${ARGS[$i]}     $GRN died  OK $RES \n"
+# 			fi
+# 			((i++))
+# 	done
+# 	((j++))
+# done
 
 
 ######################################################################
@@ -135,49 +131,49 @@ ARGS=(
 	)
 ARRLEN=${#ARGS[@]}
 
-j=0
-while [ $j -lt $CYCLES ]
-do
-	echo -e "\n${CYN}---------------------------------------------------------------------------- ${RES}"
-	echo -e "${CYN}SHOULD NOT DIE, runtime $TIME secs --------------------------------------------- ${RES}\n"
-	echo -e "${CYN}   CYCLE $j ${RES}"
-	echo "CYCLE $j" >> output_lastlines
-	i=0
-	while [ $i -lt $ARRLEN ]
-	do
-		echo -e -n "   Test $i:	${ARGS[$i]}"
-		echo -e "\n\n\n--- SHOULD NOT DIE, CYCLE $j, TEST $i ---" >> output_error
-		$TIMEOUT $TIME $FOLDERPATH/philo	${ARGS[$i]} 2>> output_error 1> output ; sleep 1
-		python3 output_check_order.py
-		ORDER=$?
-		RET=$(grep -c 'died' output)
+# j=0
+# while [ $j -lt $CYCLES ]
+# do
+# 	echo -e "\n${CYN}---------------------------------------------------------------------------- ${RES}"
+# 	echo -e "${CYN}SHOULD NOT DIE, runtime $TIME secs --------------------------------------------- ${RES}\n"
+# 	echo -e "${CYN}   CYCLE $j ${RES}"
+# 	echo "CYCLE $j" >> output_lastlines
+# 	i=0
+# 	while [ $i -lt $ARRLEN ]
+# 	do
+# 		echo -e -n "   Test $i:	${ARGS[$i]}"
+# 		echo -e "\n\n\n--- SHOULD NOT DIE, CYCLE $j, TEST $i ---" >> output_error
+# 		$TIMEOUT $TIME $FOLDERPATH/philo	${ARGS[$i]} 2>> output_error 1> output ; sleep 1
+# 		python3 output_check_order.py
+# 		ORDER=$?
+# 		RET=$(grep -c 'died' output)
 
-		if ! [ -s output ]; then
-			RET=-1
-		fi
+# 		if ! [ -s output ]; then
+# 			RET=-1
+# 		fi
 
 
-		check_last_lines $i
-		CHECK=$?
-		if [ $RET == 0 ] && [ $ORDER == 0 ]; then
-			if [ $CHECK == 0 ]; then
-				echo -e " .... $OK \n" ; sleep 1
-			fi
-		elif [ $RET == 1 ] && [ $ORDER == 0 ]; then
- 			echo -e "$RED .... died too soon (maybe due to fsanitize) $RES \n" ; sleep 1
-		elif [ $RET == 1 ] && [ $ORDER == 1 ]; then
- 			echo -e "$RED .... died too soon (maybe due to fsanitize) $RES \n" ; sleep 1
-		elif [ $RET == -1 ] ; then
-			echo -e "$RED .... empty output file (maybe runtime was too short)$RES\n"
-		fi
-		RET=$(grep -c 'data race' output_error)
-		if [ $RET -gt 0 ]; then
-			echo -e "$RED $RET .... Data Race found!\n $RES"
-		fi
-		((i++))
-	done
-	((j++))
- done
+# 		check_last_lines $i
+# 		CHECK=$?
+# 		if [ $RET == 0 ] && [ $ORDER == 0 ]; then
+# 			if [ $CHECK == 0 ]; then
+# 				echo -e " .... $OK \n" ; sleep 1
+# 			fi
+# 		elif [ $RET == 1 ] && [ $ORDER == 0 ]; then
+#  			echo -e "$RED .... died too soon (maybe due to fsanitize) $RES \n" ; sleep 1
+# 		elif [ $RET == 1 ] && [ $ORDER == 1 ]; then
+#  			echo -e "$RED .... died too soon (maybe due to fsanitize) $RES \n" ; sleep 1
+# 		elif [ $RET == -1 ] ; then
+# 			echo -e "$RED .... empty output file (maybe runtime was too short)$RES\n"
+# 		fi
+# 		RET=$(grep -c 'data race' output_error)
+# 		if [ $RET -gt 0 ]; then
+# 			echo -e "$RED $RET .... Data Race found!\n $RES"
+# 		fi
+# 		((i++))
+# 	done
+# 	((j++))
+#  done
 
 
 
@@ -195,7 +191,7 @@ do
 	do
 		echo -e -n "   Test $i:  ${ARGS[$i]} $MEALS"     ; sleep 1
 		echo -e "\n\n\n--- SHOULD STOP AFTER $MEALS MEALS, CYCLE $j, TEST $i ---" >> output_error
- 		$FOLDERPATH/philo	${ARGS[$i]} $MEALS 2>> output_error 1> output ; sleep 1
+ 		$TIMEOUT 30 $FOLDERPATH/philo	${ARGS[$i]} $MEALS 2>> output_error 1> output ; sleep 1
 		RET=$(grep -c 'died' output)
 		if ! [ -s output ]; then
 			RET=-1
